# -*- coding: utf-8 -*-
"""ITBworkshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhleyXOask8wIsD6xO0rWoa5q3Unqi0u
"""


import requests
import pandas as pd
from datetime import datetime
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"
response = requests.get(url, timeout=20)

print("Status code:", response.status_code)

import requests
import pandas as pd
from bs4 import BeautifulSoup

base_url = "https://quotes.toscrape.com"
url = base_url
rows = []

while url:
    response = requests.get(url, timeout=20)
    soup = BeautifulSoup(response.text, "html.parser")

    for quote in soup.select(".quote"):
        text = quote.select_one(".text").get_text(strip=True)
        author = quote.select_one(".author").get_text(strip=True)
        tags = [tag.get_text(strip=True) for tag in quote.select(".tag")]

        rows.append({
            "text": text,
            "author": author,
            "tags": ", ".join(tags)
        })

    # Find next page link
    next_page = soup.select_one(".next a")
    if next_page:
        url = base_url + next_page["href"]
    else:
        url = None  # No more pages, exit loop

# Create DataFrame
df = pd.DataFrame(rows)
print(f"Total quotes scraped: {len(df)}")

# Final check
print(f"Rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nSample:")




from supabase import create_client
from datetime import datetime
import pandas as pd

# ----------------------------
# Setup Supabase
# ----------------------------
import os

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
scrape_time = datetime.now().isoformat()

# ----------------------------
# Ensure tags are split and exploded
# ----------------------------
# If tags are a string, split into list
df["tags"] = df["tags"].apply(lambda x: x if isinstance(x, list) else x.split(", "))

# Explode so each tag gets its own row
df_exploded = df.explode("tags").reset_index(drop=True)

# ----------------------------
# Prepare rows for Supabase insert
# ----------------------------
rows = []
for _, row in df_exploded.iterrows():
    rows.append({
        "text":       str(row.get("text", "")),
        "author":     str(row.get("author", "")),
        "tags":       str(row.get("tags", "")),  # now each row has a single tag
        "scraped_at": scrape_time
    })

# ----------------------------
# Insert into Supabase
# ----------------------------
if rows:
    result = supabase.table("quotes").insert(rows).execute()
    print("✅ Inserted", len(rows), "quote-tag rows!")
else:
    print("⚠️ No data found to insert. Check your scraper!")